cmake_minimum_required(VERSION 3.8)
project(console_servo_stamp)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(trajectory_msgs REQUIRED)
find_package(moveit_ros_planning REQUIRED)
add_executable(model_audit src/model_audit.cpp)
ament_target_dependencies(model_audit rclcpp moveit_ros_planning)
add_executable(stamp_servo src/stamp_servo.cpp)
ament_target_dependencies(stamp_servo rclcpp trajectory_msgs)
install(TARGETS stamp_servo model_audit DESTINATION lib/${PROJECT_NAME})
ament_package()
